//Action Pannes
export const CREATE_PANNE = "CREATE_PANNE";
export const RETRIEVE_PANNES = "RETRIEVE_PANNES";
export const UPDATE_PANNE = "UPDATE_PANNE";
export const DELETE_PANNE = "DELETE_PANNE";
export const DELETE_ALL_PANNES = "DELETE_ALL_PANNES";

//Action vehicules
export const CREATE_VEHICULE = "CREATE_VEHICULE";
export const RETRIEVE_VEHICULES = "RETRIEVE_VEHICULES";
export const UPDATE_VEHICULE = "UPDATE_VEHICULE";
export const DELETE_VEHICULE = "DELETE_VEHICULE";
export const DELETE_ALL_VEHICULES = "DELETE_ALL_VEHICULES";

//Action clients
export const CREATE_CLIENT = "CREATE_CLIENT";
export const RETRIEVE_CLIENTS = "RETRIEVE_CLIENTS";
export const UPDATE_CLIENT = "UPDATE_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";
export const DELETE_ALL_CLIENTS = "DELETE_ALL_CLIENTS";

//Action Reparateurs
export const CREATE_REPARATEUR = "CREATE_REPARATEUR";
export const RETRIEVE_REPARATEURS = "RETRIEVE_REPARATEURS";
export const UPDATE_REPARATEUR = "UPDATE_REPARATEUR";
export const DELETE_REPARATEUR = "DELETE_REPARATEUR";
export const DELETE_ALL_REPARATEURS = "DELETE_ALL_REPARATEURS";

//Action questions
export const CREATE_QUESTION = "CREATE_QUESTION";
export const RETRIEVE_QUESTIONS = "RETRIEVE_QUESTIONS";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const DELETE_ALL_QUESTIONS = "DELETE_ALL_QUESTIONS";

//Action Typespannes
export const CREATE_TYPEPANNE = "CREATE_TYPEPANNE";
export const RETRIEVE_TYPEPANNES = "RETRIEVE_TYPEPANNES";
export const UPDATE_TYPEPANNE = "UPDATE_TYPEPANNE";
export const DELETE_TYPEPANNE = "DELETE_TYPEPANNE";
export const DELETE_ALL_TYPEPANNES = "DELETE_ALL_TYPEPANNES";

//Action Reponses
export const CREATE_REPONSE = "CREATE_REPONSE";
export const RETRIEVE_REPONSES = "RETRIEVE_REPONSES";
export const UPDATE_REPONSE = "UPDATE_REPONSE";
export const DELETE_REPONSE = "DELETE_REPONSE";
export const DELETE_ALL_REPONSES = "DELETE_ALL_REPONSES";

//Action Enquete
export const CREATE_ENQUETE = "CREATE_ENQUETE";
export const RETRIEVE_ENQUETES = "RETRIEVE_ENQUETES";
export const UPDATE_ENQUETE = "UPDATE_ENQUETE";
export const DELETE_ENQUETE = "DELETE_ENQUETE";
export const DELETE_ALL_ENQUETES = "DELETE_ALL_ENQUETES";

//Action Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

// Auth message
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";